CREATE SEQUENCE IF NOT EXISTS public.idgenerator
    START WITH 1000
    INCREMENT BY 50;

CREATE TABLE public.autor (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    imie character varying(15) NOT NULL,
    nazwisko character varying(25) NOT NULL
);

CREATE TABLE public.dane_ksiazki (
    isbn character varying(20) NOT NULL PRIMARY KEY,
    rok_wydania integer NOT NULL,
    tytul character varying(50) NOT NULL,
    wydawnictwo character varying(25) NOT NULL,
    okladka oid,
    opis character varying(2000),
    cena double precision
);

CREATE TABLE public.dziedzina (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nazwa character varying(50) NOT NULL
);

CREATE TABLE public.poddziedzina (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nazwa character varying(50) NOT NULL,
    dziedzina_id bigint,
    CONSTRAINT fk_dziedzina FOREIGN KEY (dziedzina_id) REFERENCES public.dziedzina(id)
);

CREATE TABLE public.rola (
    id bigint NOT NULL PRIMARY KEY,
    version integer NOT NULL,
    name character varying(255)
);

CREATE TABLE public.pracownicy (
    id bigint NOT NULL PRIMARY KEY,
    version integer NOT NULL,
    email character varying(50) NOT NULL,
    imie character varying(15) NOT NULL,
    nazwisko character varying(25) NOT NULL,
    nr_telefonu character varying(15) NOT NULL,
    password character varying(255),
    enabled boolean DEFAULT true NOT NULL
);

CREATE TABLE public.pracownik_role (
    pracownik_id bigint NOT NULL,
    rola_id bigint NOT NULL,
    PRIMARY KEY (pracownik_id, rola_id),
    CONSTRAINT fk_pracownik FOREIGN KEY (pracownik_id) REFERENCES public.pracownicy(id),
    CONSTRAINT fk_rola FOREIGN KEY (rola_id) REFERENCES public.rola(id)
);

CREATE TABLE public.uzytkownicy (
    id bigint NOT NULL PRIMARY KEY,
    version integer NOT NULL,
    email character varying(50) NOT NULL,
    imie character varying(15) NOT NULL,
    nazwisko character varying(25) NOT NULL,
    nr_telefonu character varying(15) NOT NULL,
    password character varying(255) NOT NULL,
    data_urodzenia date NOT NULL,
    enabled boolean DEFAULT false NOT NULL,
    locked boolean DEFAULT false
);

CREATE TABLE public.tlumacz (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    imie character varying(255) NOT NULL,
    nazwisko character varying(255) NOT NULL
);

CREATE TABLE public.ksiazka (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stan_fizyczny character varying(255) NOT NULL,
    status character varying(255),
    isbn_id character varying(255),
    poddziedzina_id bigint,
    licznik_wypozyczen integer DEFAULT 0 NOT NULL,
    wymaga_kontroli boolean DEFAULT false NOT NULL,
    data_ostatniej_kontroli date,
    CONSTRAINT fk_ksiazka_dane FOREIGN KEY (isbn_id) REFERENCES public.dane_ksiazki(isbn),
    CONSTRAINT fk_ksiazka_poddziedzina FOREIGN KEY (poddziedzina_id) REFERENCES public.poddziedzina(id)
);

CREATE TABLE public.wycofanie (
    id bigint NOT NULL PRIMARY KEY,
    version integer NOT NULL,
    data_wycofania date,
    powod character varying(255),
    ksiazka_id bigint NOT NULL,
    pracownik_id bigint NOT NULL,
    CONSTRAINT fk_wycofanie_ksiazka FOREIGN KEY (ksiazka_id) REFERENCES public.ksiazka(id),
    CONSTRAINT fk_wycofanie_pracownik FOREIGN KEY (pracownik_id) REFERENCES public.pracownicy(id)
);

CREATE TABLE public.wypozyczenie (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data_oddania date,
    data_wypozyczenia date,
    kara double precision,
    termin_zwrotu date,
    uzytkownik_id bigint,
    zwrot_zgloszony boolean DEFAULT false,
    przedluzone boolean DEFAULT false,
    naliczono_kare_za_zaginiecie boolean DEFAULT false,
    CONSTRAINT fk_wypozyczenie_uzytkownik FOREIGN KEY (uzytkownik_id) REFERENCES public.uzytkownicy(id)
);

CREATE TABLE public.rezerwacja (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data_rezerwacji date,
    status character varying(255),
    wazna_do date,
    zrealizowana boolean NOT NULL,
    uzytkownik_id bigint,
    CONSTRAINT fk_rezerwacja_uzytkownik FOREIGN KEY (uzytkownik_id) REFERENCES public.uzytkownicy(id)
);

CREATE TABLE public.zarezerwowana_ksiazka (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ksiazka_id bigint,
    rezerwacja_id bigint,
    CONSTRAINT fk_zark_ksiazka FOREIGN KEY (ksiazka_id) REFERENCES public.ksiazka(id),
    CONSTRAINT fk_zark_rezerwacja FOREIGN KEY (rezerwacja_id) REFERENCES public.rezerwacja(id)
);

CREATE TABLE public.wypozyczona_ksiazka (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ksiazka_id bigint,
    wypozyczenie_id bigint,
    CONSTRAINT fk_wypk_ksiazka FOREIGN KEY (ksiazka_id) REFERENCES public.ksiazka(id),
    CONSTRAINT fk_wypk_wypozyczenie FOREIGN KEY (wypozyczenie_id) REFERENCES public.wypozyczenie(id)
);

CREATE TABLE public.autor_ksiazka (
    ksiazka_id character varying(255) NOT NULL,
    autor_id bigint NOT NULL,
    PRIMARY KEY (ksiazka_id, autor_id),
    CONSTRAINT fk_autor_ksiazka_autor FOREIGN KEY (autor_id) REFERENCES public.autor(id),
    CONSTRAINT fk_autor_ksiazka_dane FOREIGN KEY (ksiazka_id) REFERENCES public.dane_ksiazki(isbn)
);

CREATE TABLE public.tlumacz_ksiazka (
    ksiazka_isbn character varying(255) NOT NULL,
    tlumacz_id bigint NOT NULL,
    PRIMARY KEY (ksiazka_isbn, tlumacz_id),
    CONSTRAINT fk_tlumacz_ksiazka_tlumacz FOREIGN KEY (tlumacz_id) REFERENCES public.tlumacz(id),
    CONSTRAINT fk_tlumacz_ksiazka_dane FOREIGN KEY (ksiazka_isbn) REFERENCES public.dane_ksiazki(isbn)
);